"""
Patient Simulator — a text-based diagnostic training tool.

Doctors pick a ward, meet a FRESHLY GENERATED patient (a random disease
from that ward combined with a randomly assembled profile — name, age,
gender, symptoms, history, medications, vitals), then interrogate the
"patient" in a Q&A loop. Answers are generated by Google's Gemini API
(free tier, generous daily request limits — no per-token billing needed
for practice use) when an API key is available, and fall back to a
lightweight rule-based responder otherwise, so the script always runs
offline.

IMPORTANT DESIGN POINT: patient profiles are NOT a hardcoded list to pick
from. Each disease defines *pools* of plausible symptoms, history factors,
medications, an age range, and vital-sign ranges. Every new session:
  1. Picks a random disease from the chosen ward.
  2. Uses Faker (if installed) to generate a brand-new name/age/gender.
  3. Randomly samples a handful of symptoms/history items/medications from
     that disease's pools.
  4. Randomizes vitals within clinically plausible ranges for that disease.
This means the pool of *possible* patients is effectively unlimited, even
though the underlying medical knowledge (which symptoms/history fit which
disease) stays curated and clinically sensible.

The core logic lives in `PatientSimulator`, a plain Python class with no
I/O side effects of its own — this is deliberate so the exact same class
can be dropped behind a FastAPI/Flask endpoint later (see the commented
`api.py` sketch at the bottom of this file) without touching the CLI code.

Run it directly for a terminal session:
    python patient_simulator.py

Optional:
    pip install faker                 -> unique random names every run
    pip install google-genai          -> LLM-generated answers via Gemini
    export GEMINI_API_KEY=AIza...      -> enables the LLM path
Without either, the script still runs fully offline with built-in fallbacks.

Getting a free Gemini API key: visit https://aistudio.google.com/apikey,
sign in with a Google account, and click "Create API key" — no credit
card required for the free tier. Free-tier daily limits are generous
(hundreds of requests/day on Flash models), which is effectively
unlimited for practicing consultations.
"""

from __future__ import annotations

import concurrent.futures
import os
import random
import sys
import textwrap
import time
from dataclasses import dataclass, field
from typing import Optional

# --------------------------------------------------------------------------
# Optional dependencies. The script must still work with neither installed.
# --------------------------------------------------------------------------
try:
    from google import genai as _genai_sdk  # pip install google-genai
    from google.genai import types as _genai_types
    _GEMINI_AVAILABLE = True
except ImportError:
    _GEMINI_AVAILABLE = False

_DEFAULT_GEMINI_MODEL = "gemini-3.5-flash-lite"

# --------------------------------------------------------------------------
# API Key Default Fallback
# --------------------------------------------------------------------------
_HARDCODED_GEMINI_API_KEY = ""

# The google-genai SDK's own timeout settings (http_options timeout=...) are
# known to be unreliable — under load a request can stall on the socket and
# never return, with no exception raised (see googleapis/python-genai#1893,
# #911, #4031). To guarantee the CLI never hangs waiting on the network, we
# run each Gemini call in a worker thread and enforce our own hard timeout
# via `future.result(timeout=...)`, regardless of what the SDK does.
_LLM_EXECUTOR = concurrent.futures.ThreadPoolExecutor(max_workers=4, thread_name_prefix="gemini-call")

try:
    from faker import Faker
    _fake = Faker()
    _FAKER_AVAILABLE = True
except ImportError:
    _FAKER_AVAILABLE = False

# Small built-in name pools used only if Faker isn't installed, so patient
# generation is still varied without any extra dependency.
_FALLBACK_MALE_NAMES = [
    "John Doe", "Robert Kim", "Harold Weiss", "Ahmed Farouk", "George Hutton",
    "Lucas Meyer", "Walter Cheng", "Bruce Malone", "Ethan Brooks", "Daniel Osei",
    "Marcus Deveraux", "Tomasz Wysocki",
]
_FALLBACK_FEMALE_NAMES = [
    "Mary Alonso", "Grace Owusu", "Delia Fontaine", "Priya Nair", "Nina Petrova",
    "Yumiko Sato", "Aisha Bello", "Fatima Rahman", "Carmen Reyes", "Sofia Marchetti",
    "Linda Choi", "Rachel Simmons",
]


# ==========================================================================
# 1. DATA: wards -> diseases -> GENERATION POOLS (not fixed profiles)
# ==========================================================================
# Minimum required: 3 wards, 3 diseases per ward. Each disease defines pools
# that a fresh patient is randomly assembled from every time.
#
#   symptom_pool     -> sample 2-3 per patient
#   history_pool     -> sample 1-2 per patient
#   medication_pool  -> sample 0-2 per patient ("None currently" if 0)
#   age_range        -> (min, max) plausible age for this condition
#   vitals_ranges    -> (min, max) per vital sign, randomized per patient

WARDS = {
    "Cardiology": {
        "diseases": [
            {
                "name": "Myocardial Infarction",
                "symptom_pool": [
                    "crushing chest pain", "pain radiating to the left arm",
                    "shortness of breath", "cold sweat", "nausea",
                    "a feeling of impending doom", "dizziness",
                ],
                "history_pool": [
                    "smoker", "hypertensive", "family history of heart disease",
                    "high cholesterol", "previous minor heart attack",
                ],
                "medication_pool": ["Aspirin", "Atorvastatin", "Metoprolol", "Nitroglycerin as needed"],
                "age_range": (45, 78),
                "vitals_ranges": {"BP_sys": (140, 170), "BP_dia": (85, 105),
                                   "HR": (95, 125), "Temp": (36.8, 37.4), "SpO2": (90, 95)},
            },
            {
                "name": "Atrial Fibrillation",
                "symptom_pool": [
                    "palpitations", "irregular heartbeat", "dizziness", "fatigue",
                    "shortness of breath on exertion", "occasional chest discomfort",
                ],
                "history_pool": [
                    "hyperthyroidism", "heavy caffeine intake", "hypertension",
                    "history of binge drinking", "prior mild stroke",
                ],
                "medication_pool": ["Warfarin", "Apixaban", "Bisoprolol", "Levothyroxine"],
                "age_range": (55, 82),
                "vitals_ranges": {"BP_sys": (120, 145), "BP_dia": (75, 95),
                                   "HR": (110, 150), "Temp": (36.5, 37.0), "SpO2": (95, 99)},
            },
            {
                "name": "Heart Failure",
                "symptom_pool": [
                    "swelling in the legs and ankles", "breathlessness when lying flat",
                    "fatigue", "night-time cough", "reduced exercise tolerance",
                    "rapid weight gain from fluid retention",
                ],
                "history_pool": [
                    "previous heart attack", "long-standing hypertension",
                    "mild kidney impairment", "diabetes",
                ],
                "medication_pool": ["Furosemide", "Ramipril", "Bisoprolol", "Spironolactone"],
                "age_range": (60, 85),
                "vitals_ranges": {"BP_sys": (130, 155), "BP_dia": (80, 95),
                                   "HR": (85, 105), "Temp": (36.5, 37.0), "SpO2": (88, 94)},
            },
        ]
    },
    "Neurology": {
        "diseases": [
            {
                "name": "Migraine",
                "symptom_pool": [
                    "throbbing one-sided headache", "sensitivity to light",
                    "sensitivity to sound", "nausea", "visual aura before the headache",
                ],
                "history_pool": [
                    "family history of migraines", "high stress at work",
                    "poor sleep schedule", "history of motion sickness",
                ],
                "medication_pool": ["Ibuprofen", "Sumatriptan", "None regularly"],
                "age_range": (18, 45),
                "vitals_ranges": {"BP_sys": (110, 125), "BP_dia": (70, 82),
                                   "HR": (70, 88), "Temp": (36.5, 37.0), "SpO2": (98, 100)},
            },
            {
                "name": "Epilepsy (Seizure Disorder)",
                "symptom_pool": [
                    "sudden jerking movements", "brief loss of awareness",
                    "confusion after the episode", "biting of the tongue during episodes",
                    "an unusual warning feeling before an episode",
                ],
                "history_pool": [
                    "diagnosed with epilepsy in childhood", "head injury in the past",
                    "occasionally misses medication doses", "sleep deprivation as a trigger",
                ],
                "medication_pool": ["Levetiracetam", "Lamotrigine", "Valproate"],
                "age_range": (12, 40),
                "vitals_ranges": {"BP_sys": (110, 130), "BP_dia": (70, 85),
                                   "HR": (75, 95), "Temp": (36.5, 37.1), "SpO2": (96, 99)},
            },
            {
                "name": "Parkinson's Disease",
                "symptom_pool": [
                    "hand tremor at rest", "stiffness in the limbs",
                    "slowed movement", "soft or quiet voice", "shuffling walk",
                ],
                "history_pool": [
                    "symptoms crept in gradually over the last couple of years",
                    "no clear family history", "occasional falls recently",
                ],
                "medication_pool": ["Levodopa/Carbidopa", "Pramipexole"],
                "age_range": (58, 80),
                "vitals_ranges": {"BP_sys": (115, 140), "BP_dia": (72, 88),
                                   "HR": (68, 85), "Temp": (36.4, 36.9), "SpO2": (96, 99)},
            },
        ]
    },
    "Respiratory": {
        "diseases": [
            {
                "name": "Asthma Exacerbation",
                "symptom_pool": [
                    "wheezing", "tight chest", "difficulty breathing",
                    "persistent cough", "shortness of breath with exercise",
                ],
                "history_pool": [
                    "asthma since childhood", "seasonal allergies", "pet allergy",
                    "recent upper respiratory infection",
                ],
                "medication_pool": ["Salbutamol inhaler", "Fluticasone inhaler"],
                "age_range": (8, 40),
                "vitals_ranges": {"BP_sys": (110, 130), "BP_dia": (70, 85),
                                   "HR": (95, 118), "Temp": (36.6, 37.2), "SpO2": (90, 95)},
            },
            {
                "name": "Community-Acquired Pneumonia",
                "symptom_pool": [
                    "fever", "productive cough with colored phlegm",
                    "sharp chest pain when breathing deeply", "chills", "fatigue",
                ],
                "history_pool": [
                    "long-time smoker", "recently had the flu", "mild COPD",
                    "no significant prior lung disease",
                ],
                "medication_pool": ["Paracetamol", "Salbutamol inhaler as needed", "None currently"],
                "age_range": (35, 75),
                "vitals_ranges": {"BP_sys": (100, 120), "BP_dia": (65, 80),
                                   "HR": (100, 120), "Temp": (38.3, 39.5), "SpO2": (88, 93)},
            },
            {
                "name": "Chronic Obstructive Pulmonary Disease (COPD)",
                "symptom_pool": [
                    "chronic cough with phlegm", "shortness of breath on exertion",
                    "wheezing", "reduced exercise tolerance", "chest tightness in cold weather",
                ],
                "history_pool": [
                    "long smoking history", "former smoker who quit years ago",
                    "childhood exposure to biomass smoke", "recurrent chest infections",
                ],
                "medication_pool": ["Tiotropium inhaler", "Salmeterol/Fluticasone inhaler", "Home oxygen at night"],
                "age_range": (55, 80),
                "vitals_ranges": {"BP_sys": (120, 145), "BP_dia": (75, 92),
                                   "HR": (85, 105), "Temp": (36.5, 37.0), "SpO2": (86, 92)},
            },
        ]
    },
    "GI": {
        "diseases": [
            {
                "name": "Acute Appendicitis",
                "symptom_pool": [
                    "pain that started near the belly button and moved to the lower right abdomen",
                    "nausea", "loss of appetite", "low-grade fever", "pain worse on movement",
                ],
                "history_pool": [
                    "no prior abdominal surgery", "symptoms started within the last day",
                    "no significant medical history",
                ],
                "medication_pool": ["None"],
                "age_range": (15, 35),
                "vitals_ranges": {"BP_sys": (110, 125), "BP_dia": (68, 80),
                                   "HR": (92, 110), "Temp": (37.8, 38.6), "SpO2": (97, 100)},
            },
            {
                "name": "Gastroesophageal Reflux Disease (GERD)",
                "symptom_pool": [
                    "burning chest pain after meals", "sour taste in the mouth",
                    "worse symptoms when lying down", "occasional regurgitation of food",
                ],
                "history_pool": [
                    "overweight", "drinks coffee daily", "eats large meals late at night",
                    "occasional spicy food intolerance",
                ],
                "medication_pool": ["Omeprazole", "Over-the-counter antacids"],
                "age_range": (30, 60),
                "vitals_ranges": {"BP_sys": (115, 130), "BP_dia": (72, 84),
                                   "HR": (70, 85), "Temp": (36.5, 36.9), "SpO2": (98, 100)},
            },
            {
                "name": "Irritable Bowel Syndrome (IBS)",
                "symptom_pool": [
                    "cramping abdominal pain", "bloating",
                    "alternating diarrhea and constipation", "urgency after eating",
                ],
                "history_pool": [
                    "symptoms worsen with stress", "notices dairy makes it worse",
                    "symptoms ongoing for several months", "high-stress job",
                ],
                "medication_pool": ["Fiber supplement", "None regularly"],
                "age_range": (20, 45),
                "vitals_ranges": {"BP_sys": (108, 122), "BP_dia": (68, 80),
                                   "HR": (70, 85), "Temp": (36.5, 36.9), "SpO2": (98, 100)},
            },
        ]
    },
    "Endocrinology": {
        "diseases": [
            {
                "name": "Type 2 Diabetes Mellitus",
                "symptom_pool": [
                    "increased thirst", "frequent urination", "fatigue",
                    "blurred vision", "slow-healing wounds", "unexplained weight loss",
                ],
                "history_pool": [
                    "family history of diabetes", "obesity", "sedentary lifestyle",
                    "gestational diabetes in the past",
                ],
                "medication_pool": ["Metformin", "Insulin", "Glipizide", "None currently"],
                "age_range": (40, 75),
                "vitals_ranges": {"BP_sys": (120, 145), "BP_dia": (75, 90),
                                   "HR": (70, 90), "Temp": (36.5, 37.0), "SpO2": (96, 99)},
            },
            {
                "name": "Hypothyroidism",
                "symptom_pool": [
                    "fatigue", "unexplained weight gain", "feeling cold all the time",
                    "dry skin", "constipation", "hair thinning",
                ],
                "history_pool": [
                    "family history of thyroid disease", "prior radiation to the neck",
                    "autoimmune condition", "recent childbirth",
                ],
                "medication_pool": ["Levothyroxine", "None currently"],
                "age_range": (30, 65),
                "vitals_ranges": {"BP_sys": (105, 125), "BP_dia": (65, 80),
                                   "HR": (55, 70), "Temp": (36.0, 36.5), "SpO2": (97, 99)},
            },
            {
                "name": "Hyperthyroidism (Graves' Disease)",
                "symptom_pool": [
                    "rapid heartbeat", "unexplained weight loss", "heat intolerance",
                    "tremor in the hands", "anxiety", "increased sweating",
                ],
                "history_pool": [
                    "family history of thyroid disease", "autoimmune condition",
                    "recent high stress",
                ],
                "medication_pool": ["Methimazole", "Propranolol", "None currently"],
                "age_range": (20, 50),
                "vitals_ranges": {"BP_sys": (110, 135), "BP_dia": (65, 85),
                                   "HR": (100, 130), "Temp": (37.0, 37.6), "SpO2": (97, 99)},
            },
        ]
    },
    "Renal": {
        "diseases": [
            {
                "name": "Acute Kidney Injury",
                "symptom_pool": [
                    "decreased urine output", "swelling in the legs", "fatigue",
                    "nausea", "confusion",
                ],
                "history_pool": [
                    "recent severe dehydration", "recent NSAID use",
                    "recent infection or sepsis", "diabetes",
                ],
                "medication_pool": ["None currently", "Furosemide"],
                "age_range": (40, 80),
                "vitals_ranges": {"BP_sys": (95, 140), "BP_dia": (60, 90),
                                   "HR": (85, 110), "Temp": (36.5, 38.0), "SpO2": (92, 97)},
            },
            {
                "name": "Chronic Kidney Disease",
                "symptom_pool": [
                    "fatigue", "swelling in the ankles", "foamy urine",
                    "poor appetite", "itchy skin",
                ],
                "history_pool": [
                    "long-standing diabetes", "long-standing hypertension",
                    "family history of kidney disease",
                ],
                "medication_pool": ["Lisinopril", "Furosemide", "Erythropoietin injections"],
                "age_range": (50, 80),
                "vitals_ranges": {"BP_sys": (135, 160), "BP_dia": (85, 100),
                                   "HR": (75, 95), "Temp": (36.5, 37.0), "SpO2": (94, 98)},
            },
            {
                "name": "Kidney Stones (Nephrolithiasis)",
                "symptom_pool": [
                    "sudden severe pain in the side and back", "blood in the urine",
                    "pain radiating to the groin", "nausea", "frequent urge to urinate",
                ],
                "history_pool": [
                    "previous kidney stones", "low fluid intake",
                    "family history of kidney stones",
                ],
                "medication_pool": ["Pain relievers as needed", "Tamsulosin"],
                "age_range": (25, 55),
                "vitals_ranges": {"BP_sys": (118, 140), "BP_dia": (75, 90),
                                   "HR": (90, 115), "Temp": (36.7, 37.3), "SpO2": (97, 100)},
            },
        ]
    },
    "Infectious Disease": {
        "diseases": [
            {
                "name": "Urinary Tract Infection",
                "symptom_pool": [
                    "burning sensation when urinating", "frequent urge to urinate",
                    "cloudy urine", "lower abdominal discomfort", "mild fever",
                ],
                "history_pool": [
                    "previous UTIs", "recent sexual activity", "diabetes",
                ],
                "medication_pool": ["Nitrofurantoin", "None currently"],
                "age_range": (20, 60),
                "vitals_ranges": {"BP_sys": (110, 125), "BP_dia": (70, 82),
                                   "HR": (80, 100), "Temp": (37.5, 38.5), "SpO2": (97, 100)},
            },
            {
                "name": "Cellulitis",
                "symptom_pool": [
                    "red and swollen skin", "warmth over the affected area",
                    "pain at the site", "fever", "chills",
                ],
                "history_pool": [
                    "recent skin injury or insect bite", "diabetes", "poor circulation",
                ],
                "medication_pool": ["Cephalexin (antibiotic)", "Pain relievers as needed"],
                "age_range": (30, 70),
                "vitals_ranges": {"BP_sys": (112, 130), "BP_dia": (70, 85),
                                   "HR": (90, 115), "Temp": (37.8, 39.0), "SpO2": (95, 99)},
            },
            {
                "name": "Influenza",
                "symptom_pool": [
                    "sudden high fever", "body aches", "sore throat",
                    "dry cough", "extreme fatigue", "chills",
                ],
                "history_pool": [
                    "no flu vaccine this season", "close contact with someone sick",
                    "no significant prior illness",
                ],
                "medication_pool": ["Paracetamol", "Oseltamivir", "None currently"],
                "age_range": (15, 65),
                "vitals_ranges": {"BP_sys": (108, 125), "BP_dia": (68, 82),
                                   "HR": (90, 115), "Temp": (38.5, 39.8), "SpO2": (94, 98)},
            },
        ]
    },
    "Orthopedics": {
        "diseases": [
            {
                "name": "Hip Fracture",
                "symptom_pool": [
                    "severe hip pain after a fall", "inability to bear weight on the leg",
                    "leg appears shortened or rotated", "bruising and swelling around the hip",
                ],
                "history_pool": [
                    "osteoporosis", "recent fall at home", "long-term steroid use",
                ],
                "medication_pool": ["Calcium and Vitamin D supplements", "Pain relievers as needed"],
                "age_range": (65, 90),
                "vitals_ranges": {"BP_sys": (110, 140), "BP_dia": (65, 85),
                                   "HR": (85, 105), "Temp": (36.6, 37.2), "SpO2": (93, 97)},
            },
            {
                "name": "Osteoarthritis of the Knee",
                "symptom_pool": [
                    "knee pain that worsens with activity", "stiffness in the morning",
                    "swelling around the joint", "a grinding sensation when moving the knee",
                ],
                "history_pool": [
                    "years of joint overuse", "family history of arthritis", "being overweight",
                ],
                "medication_pool": ["Paracetamol", "Ibuprofen", "None currently"],
                "age_range": (50, 80),
                "vitals_ranges": {"BP_sys": (118, 140), "BP_dia": (75, 90),
                                   "HR": (70, 88), "Temp": (36.5, 36.9), "SpO2": (97, 99)},
            },
            {
                "name": "Lumbar Disc Herniation",
                "symptom_pool": [
                    "lower back pain radiating down the leg", "numbness or tingling in the foot",
                    "pain that is worse when sitting", "muscle weakness in the leg",
                ],
                "history_pool": [
                    "heavy manual labor job", "previous back injury", "prolonged sitting at work",
                ],
                "medication_pool": ["Ibuprofen", "Muscle relaxants", "None currently"],
                "age_range": (30, 55),
                "vitals_ranges": {"BP_sys": (115, 135), "BP_dia": (72, 88),
                                   "HR": (70, 90), "Temp": (36.5, 36.9), "SpO2": (98, 100)},
            },
        ]
    },
}


# ==========================================================================
# 2. Core simulator class — no I/O, safe to reuse behind a web API
# ==========================================================================

@dataclass
class Patient:
    ward: str
    disease: str
    name: str
    age: int
    gender: str
    symptoms: str
    history: str
    medications: str
    vitals: dict


def _generate_name_and_gender() -> tuple[str, str]:
    """Return a freshly generated (name, gender) pair each call."""
    gender = random.choice(["Male", "Female"])
    if _FAKER_AVAILABLE:
        name = _fake.name_male() if gender == "Male" else _fake.name_female()
    else:
        pool = _FALLBACK_MALE_NAMES if gender == "Male" else _FALLBACK_FEMALE_NAMES
        # Combine a random first + random last name from the pool's parts so
        # repeated sessions don't quickly repeat the exact same person.
        first = random.choice(pool).split()[0]
        last = random.choice(pool).split()[-1]
        name = f"{first} {last}"
    return name, gender


def _generate_vitals(vitals_ranges: dict) -> dict:
    bp_sys = random.randint(*vitals_ranges["BP_sys"])
    bp_dia = random.randint(*vitals_ranges["BP_dia"])
    hr = random.randint(*vitals_ranges["HR"])
    temp = round(random.uniform(*vitals_ranges["Temp"]), 1)
    spo2 = random.randint(*vitals_ranges["SpO2"])
    return {"BP": f"{bp_sys}/{bp_dia}", "HR": str(hr), "Temp": f"{temp}C", "SpO2": f"{spo2}%"}


def generate_patient(ward_name: str) -> Patient:
    """Randomly assemble a brand-new patient for `ward_name`. Called fresh
    every session — never reads from a fixed list of pre-made profiles."""
    if ward_name not in WARDS:
        raise ValueError(f"Unknown ward: {ward_name}")

    disease = random.choice(WARDS[ward_name]["diseases"])
    name, gender = _generate_name_and_gender()
    age = random.randint(*disease["age_range"])

    n_symptoms = random.randint(2, min(3, len(disease["symptom_pool"])))
    n_history = random.randint(1, min(2, len(disease["history_pool"])))
    n_meds = random.randint(0, min(2, len(disease["medication_pool"])))

    symptoms = ", ".join(random.sample(disease["symptom_pool"], n_symptoms))
    history = ", ".join(random.sample(disease["history_pool"], n_history))
    meds_sample = random.sample(disease["medication_pool"], n_meds) if n_meds else []
    medications = ", ".join(meds_sample) if meds_sample else "None currently"

    vitals = _generate_vitals(disease["vitals_ranges"])

    return Patient(
        ward=ward_name,
        disease=disease["name"],
        name=name,
        age=age,
        gender=gender,
        symptoms=symptoms,
        history=history,
        medications=medications,
        vitals=vitals,
    )


@dataclass
class PatientSimulator:
    """Holds one active patient session and answers doctor questions."""

    patient: Optional[Patient] = None
    conversation: list = field(default_factory=list)  # [(question, answer), ...]
    _client: Optional["object"] = None
    _model_name: str = _DEFAULT_GEMINI_MODEL

    def __post_init__(self) -> None:
        api_key = (
            os.environ.get("GEMINI_API_KEY")
            or os.environ.get("GOOGLE_API_KEY")
            or _HARDCODED_GEMINI_API_KEY
        )
        self._model_name = os.environ.get("GEMINI_MODEL", _DEFAULT_GEMINI_MODEL)
        if _GEMINI_AVAILABLE and api_key:
            try:
                self._client = _genai_sdk.Client(api_key=api_key)
            except Exception:
                self._client = None

    # -- session setup ----------------------------------------------------

    def list_wards(self) -> list:
        return list(WARDS.keys())

    def start_session(self, ward_name: str) -> Patient:
        """Generate a brand-new patient for `ward_name` and start a session."""
        self.patient = generate_patient(ward_name)
        self.conversation = []
        return self.patient

    # -- Q&A ----------------------------------------------------------------

    def ask(self, question: str, api_key: Optional[str] = None) -> str:
        """Return the patient's natural answer to `question`."""
        if self.patient is None:
            raise RuntimeError("No active patient session. Call start_session() first.")

        # Dynamically initialize or update client if an API key is provided
        effective_key = (
            api_key
            or os.environ.get("GEMINI_API_KEY")
            or os.environ.get("GOOGLE_API_KEY")
            or _HARDCODED_GEMINI_API_KEY
        )
        if _GEMINI_AVAILABLE and effective_key and (self._client is None or api_key):
            try:
                self._client = _genai_sdk.Client(api_key=effective_key)
            except Exception:
                pass

        if self._client is not None:
            answer = self._ask_llm(question)
        else:
            answer = self._ask_fallback(question)

        self.conversation.append((question, answer))
        return answer

    def _system_prompt(self) -> str:
        p = self.patient
        return textwrap.dedent(f"""
            You are role-playing as a patient in a medical training simulator.
            You are {p.name}, a {p.age}-year-old {p.gender}.
            You have been diagnosed (unknown to you, the doctor is diagnosing you) with: {p.disease}.
            Your symptoms: {p.symptoms}.
            Relevant medical history: {p.history}.
            Current medications: {p.medications}.
            Vital signs (only reveal if asked directly): {p.vitals}.

            Rules:
            - Always answer in the FIRST PERSON as the patient.
            - Answer naturally in 1 to 3 realistic sentences. Express your pain, feelings, and concern as a patient speaking to a physician.
            - Stay strictly consistent with your symptoms ({p.symptoms}) and medical history ({p.history}).
            - Use plain layperson language. Do not state your medical diagnosis name unless the doctor already diagnosed you.
            - If asked something unrelated to your case, answer briefly and naturally.
        """).strip()

    def _call_gemini_sync(self, question: str):
        """The actual blocking network call — run inside a worker thread so
        the caller can enforce a hard timeout on it."""
        config = _genai_types.GenerateContentConfig(
            system_instruction=self._system_prompt(),
            temperature=0.7,
            max_output_tokens=300,
        )
        
        # Deduplicated list of models to try
        candidate_models = []
        for m in [self._model_name, "gemini-3.5-flash-lite", "gemini-3.5-flash", "gemini-3.7-flash", "gemini-3.6-flash"]:
            if m and m not in candidate_models:
                candidate_models.append(m)

        last_error = None
        for m in candidate_models:
            try:
                return self._client.models.generate_content(
                    model=m,
                    contents=question,
                    config=config,
                )
            except Exception as e:
                last_error = e
                continue

        if last_error:
            raise last_error

    def _ask_llm(self, question: str) -> str:
        max_attempts = 3
        base_delay = 1.5
        request_timeout = 15

        for attempt in range(1, max_attempts + 1):
            reason = None
            is_transient = False
            try:
                future = _LLM_EXECUTOR.submit(self._call_gemini_sync, question)
                resp = future.result(timeout=request_timeout)
                text = (resp.text or "").strip()
                return text if text else self._ask_fallback(question)
            except concurrent.futures.TimeoutError:
                reason = f"no response after {request_timeout}s"
                is_transient = True
            except Exception as exc:
                reason = str(exc)
                is_transient = any(code in reason for code in ("503", "UNAVAILABLE", "429", "RESOURCE_EXHAUSTED"))

            if is_transient and attempt < max_attempts:
                delay = base_delay * (2 ** (attempt - 1))
                time.sleep(delay)
                continue
            return self._ask_fallback(question)

    # -- offline fallback responder ---------------------------------------

    def _ask_fallback(self, question: str) -> str:
        p = self.patient
        q = question.lower()

        if any(w in q for w in ["how are you", "how do you feel", "feeling", "what brings"]):
            return f"Honestly doctor, I'm feeling quite unwell. I've been experiencing severe {p.symptoms.lower()}, and it's making me really concerned."
        if any(w in q for w in ["pain", "hurt", "ache", "discomfort", "symptom"]):
            return f"Yes doctor, it started recently as a very uncomfortable {p.symptoms.split(',')[0].lower()}. It gets worse when I move around."
        if any(w in q for w in ["history", "before", "past", "previous", "prior"]):
            return f"Well, in my medical past I've dealt with {p.history.lower()}. Otherwise I try to take care of myself."
        if any(w in q for w in ["medication", "medicine", "drug", "pill", "taking"]):
            return f"I am currently taking {p.medications.lower()} as prescribed by my doctor."
        if any(w in q for w in ["age", "old"]):
            return f"I'm {p.age} years old."
        if any(w in q for w in ["smoke", "smoking", "alcohol", "drink", "lifestyle"]):
            return f"Regarding my habits, {p.history.lower()}."
        if any(w in q for w in ["vital", "blood pressure", "heart rate", "temperature", "oxygen"]):
            v = p.vitals
            return f"My latest vital check showed blood pressure of {v['BP']}, heart rate of {v['HR']} BPM, temperature of {v['Temp']}, and oxygen at {v['SpO2']}."
        if any(w in q for w in ["name", "who are you"]):
            return f"My name is {p.name}, doctor."
        if any(w in q for w in ["when", "start", "long", "onset", "time"]):
            return "It started a couple of days ago very suddenly, and it's been progressively getting worse since yesterday."
        return f"Mainly it's the {p.symptoms.split(',')[0].lower()} that's bothering me the most right now, doctor."
        if "when" in q and "start" in q:
            return "It started a couple of days ago and has been getting worse since."
        # generic catch-all, still grounded in the case
        return f"It's mainly the {p.symptoms.split(',')[0].lower()} that's bothering me most right now."


# ==========================================================================
# 3. CLI front-end
# ==========================================================================

def _print_header(text: str) -> None:
    print("\n" + "=" * 60)
    print(text)
    print("=" * 60)


def choose_ward(sim: PatientSimulator) -> str:
    wards = sim.list_wards()
    _print_header("Select a Ward")
    for i, w in enumerate(wards, start=1):
        print(f"  {i}. {w}")

    while True:
        raw = input("\nEnter a number or ward name: ").strip()
        if raw.isdigit() and 1 <= int(raw) <= len(wards):
            return wards[int(raw) - 1]
        for w in wards:
            if raw.lower() == w.lower():
                return w
        print("Invalid choice — please enter a valid number or ward name from the list.")


def print_patient_details(patient: Patient) -> None:
    _print_header("New Patient (freshly generated)")
    print(f"  Name:            {patient.name}")
    print(f"  Age / Gender:    {patient.age} / {patient.gender}")
    print(f"  Presenting with: {patient.symptoms}")
    print(f"  Medical history: {patient.history}")
    print(f"  Medications:     {patient.medications}")
    print(f"  Vitals:          " + ", ".join(f"{k}: {v}" for k, v in patient.vitals.items()))
    print("\n  Type your questions to the patient below. Type 'end' to finish the case.")


def run_cli() -> None:
    sim = PatientSimulator()

    if sim._client is None:
        print("[info] No Gemini API key found (or `google-genai` not installed) — "
              "running with the built-in offline responder.\n"
              "       Get a free key at https://aistudio.google.com/apikey, then:\n"
              "         pip install google-genai\n"
              "         export GEMINI_API_KEY=your_key_here")
    else:
        print(f"[info] Using Gemini model: {sim._model_name}")
    if not _FAKER_AVAILABLE:
        print("[info] Faker not installed — using a small built-in name pool instead (`pip install faker` for more variety).")

    ward = choose_ward(sim)
    patient = sim.start_session(ward)
    print_patient_details(patient)

    _print_header(f"Consultation — {patient.name} ({sim.patient.disease}) [hidden from doctor]")
    print("(The diagnosis above is hidden from you in a real exercise; shown here for demo purposes.)")

    while True:
        question = input("\nDoctor: ").strip()
        if not question:
            continue
        if question.strip().lower() == "end":
            print(f"\nPatient: Thank you, doctor. Goodbye and take care!")
            break
        answer = sim.ask(question)
        print(f"Patient: {answer}")


if __name__ == "__main__":
    try:
        run_cli()
    except (KeyboardInterrupt, EOFError):
        print("\n\nSession ended.")


# ==========================================================================
# 4. Sketch: exposing this as a REST API (FastAPI) for a Unity client
# ==========================================================================
# The PatientSimulator class above has zero print()/input() calls, so it can
# be wrapped directly. A minimal FastAPI service would look like this
# (kept here as a commented reference — install with `pip install fastapi
# uvicorn` and save as api.py to run):
#
# from fastapi import FastAPI, HTTPException
# from pydantic import BaseModel
# from patient_simulator import PatientSimulator, WARDS
#
# app = FastAPI()
# sessions: dict[str, PatientSimulator] = {}  # session_id -> simulator
#
# class StartRequest(BaseModel):
#     session_id: str
#     ward: str
#
# class AskRequest(BaseModel):
#     session_id: str
#     question: str
#
# @app.get("/wards")
# def get_wards():
#     return list(WARDS.keys())
#
# @app.post("/session/start")
# def start(req: StartRequest):
#     sim = PatientSimulator()
#     try:
#         patient = sim.start_session(req.ward)   # generates a NEW patient every call
#     except ValueError as e:
#         raise HTTPException(status_code=400, detail=str(e))
#     sessions[req.session_id] = sim
#     return {"name": patient.name, "age": patient.age, "gender": patient.gender,
#             "symptoms": patient.symptoms, "vitals": patient.vitals}
#
# @app.post("/session/ask")
# def ask(req: AskRequest):
#     sim = sessions.get(req.session_id)
#     if sim is None:
#         raise HTTPException(status_code=404, detail="Session not found")
#     return {"answer": sim.ask(req.question)}
#
# Run with: uvicorn api:app --reload
# Unity would then call these endpoints via UnityWebRequest / HttpClient,
# keeping one session_id per active in-game consultation.
